#!/bin/bash

VERSION=`echo $0 | /bin/sed -e 's/.*\-\([0-9]\.[0-9]\)/\1/'`

SVNROOTPATH=`ls -d /opt/CollabNetSubversion-client-${VERSION}.*`

export LD_LIBRARY_PATH="${SVNROOTPATH}/lib"

${SVNROOTPATH}/bin/svn $*
